### ISSUE TITLE
duck.com incorrectly listed as a disposable email service

### ISSUE THREAD

**Issue by astroblaster** [Dahoom152/disposable-email#2]
Hello,

I'm writing as a postmaster for duck.com, DuckDuckGo's email forwarding service.

It seems we've landed on your list as a disposable email. We don't intend for our service to be used as a disposable email. We take any reports of abuse seriously. Would you consider removing this entry?

Thank you,

Brian Kowalewicz

**Comment by Dahoom152** [comment]
Collection is automated and it seems that the source has not been updated for a while, I've updated it now and the updated sources no longer contain duck.com.

Thanks for pointing that out!

**Comment by Dahoom152** [comment]
Collection is automated and it seems that the source has not been updated for a while, I've updated it now and the updated sources no longer contain duck.com.

Thanks for pointing that out!

**Comment by Dahoom152** [comment]
Collection is automated and it seems that the source has not been updated for a while, I've updated it now and the updated sources no longer contain duck.com.

Thanks for pointing that out!
